# Generated by Django 5.1.4 on 2025-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('hint_selection', models.CharField(max_length=255)),
                ('hint_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('preference', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=255)),
                ('time_required', models.IntegerField(help_text='Time required in minutes')),
                ('importance', models.IntegerField(help_text='Rate importance from 1-10')),
                ('number_of_topics', models.IntegerField()),
            ],
        ),
    ]
